### PR TITLE
Issue 46

### LINKED ISSUE #46: Post files does not work (php7.1)
POSTing files does not work as intended. 

This is what I'd like to do:

```
$file = new \CURLFile($filePath, mime_content_type($filePath), 'file_post_name');
$data = array(
	'mode' => 'import',
	'file' => $file,
);
$this->curl->setHeader('Accept', 'application/json');
$this->curl->setHeader('Content-Type', 'application/json');
$this->curl->post('http://example.com', $data);
$this->curl->close();
```

However what is posted is a string representation of the data, including the CURLFile instance, not the actual file. I.e: 

`mode=import&file%5Bname%5D=path/to/file/&file%5Bmime%5D=mime_type_of_file&file%5Bpostname%5D=file_post_name`

This is due to the `preparePayload` method - that runs `http_build_query` on the data. If I remove those lines everything works as expected.

The library should include a way to skip `http_build_query`, or a special method for adding a file to the posted data.

Thanks

### PR DESCRIPTION
**Pull request by nadar**
this closes #46

### CODE REVIEW

File: src/Curl/Curl.php [hunk 1]
```diff
@@ -232,7 +232,19 @@ protected function preparePayload($data)
...
+                // If a value is an instance of CurlFile skip the http_build_query
+                // see issue https://github.com/php-mod/curl/issues/46
+                // suggestion from: https://stackoverflow.com/a/36603038/4611030
+                if ($value instanceof \CurlFile) {
+                    $skip = true;
+                }
+            }
+            
+            if (!$skip) {
+                $data = http_build_query($data);
```
Comment (amouhzi) [inline src/Curl/Curl.php]: We cannot skip http_build_query if there is a CurlFile, we should work arround this by using something like: https://stackoverflow.com/a/35741943

Comment (nadar) [reply src/Curl/Curl.php]: I tested on local application, it works fine, at least it's sending expected content to the API when skipping http_build_query as long as CurlFile is available. If you have another solution, its fine for me as well. This is a very urgent issue for your headless library.

**Comment by amouhzi** [comment]
This is merged, I will add more tests for that.
