### PR TITLE
Small Cosmetic modifications

### LINKED ISSUE #51: Request: RuntimeException in constructor
I have noticed that the constructor throws an **ErrorException** and the IDE always marks the warning that the Exception is not captured, so I propose to change it for **RuntimeException** since the dependency of the library is in execution time and not process.

### PR DESCRIPTION
**Pull request by evilangelmd**
In this patch i adjusted phpdocs, because there was some misspell.
I used (where is possible) getters #58 #59, (ex: $this->getHttpStatus() instead of $this->http_status_code)
Added function setVerbose instead of verbose.
Fixes #51

### CODE REVIEW

File: src/Curl/Curl.php [hunk 1]
```diff
@@ -109,12 +109,12 @@ class Curl
...
 
     /**
-     * @var bool Whether an error occured or not
+     * @var bool Whether an error occurred or not
      */
     public $http_error = false;
 
     /**
-     * @var int Contains the status code of the current processed request.
+     * @var integer Contains the status code of the current processed request.
```
Comment (amouhzi) [inline src/Curl/Curl.php]: I prefer short form here.

https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide-meta.md#43-enforcing-short-form-for-all-type-keywords

The PSR is not yet accepted, but it makes sense to use short forms.

File: src/Curl/Curl.php [hunk 2]
```diff
@@ -124,19 +124,19 @@ class Curl
...
+     * @var string|array TBD (ensure type) Contains the response header information
      */
     public $response_headers = array();
 
     /**
-     * @var string Contains the response from the curl request
+     * @var string|false Contains the response from the curl request
      */
-    public $response = null;
+    public $response = false;
```
Comment (amouhzi) [inline src/Curl/Curl.php]: This can break libraries using it.

File: src/Curl/Curl.php [hunk 3]
```diff
@@ -146,12 +146,12 @@ class Curl
     /**
      * Constructor ensures the available curl extension is loaded.
      *
-     * @throws \ErrorException
+     * @throws \RuntimeException
```
Comment (amouhzi) [inline src/Curl/Curl.php]: This can break libraries using it. This will involve making a major version. But you are right.

File: src/Curl/Curl.php (hunk 2 above)
Comment (evilangelmd) [reply src/Curl/Curl.php]: as from php.net/curl docs, when curl_exec fails it returns false. so in this case $response will be false. in this case i think will be better when response is not set to return always false, instead of null|false|string

File: src/Curl/Curl.php (hunk 1 above)
Comment (evilangelmd) [reply src/Curl/Curl.php]: i can admit this. i will make tomorrow a commit with short form

File: src/Curl/Curl.php (hunk 2 above)
Comment (evilangelmd) [reply src/Curl/Curl.php]: > Returns TRUE on success or FALSE on failure. However, if the CURLOPT_RETURNTRANSFER option is set, it will return the result on success, FALSE on failure.

File: src/Curl/Curl.php (hunk 3 above)
Comment (nadar) [reply src/Curl/Curl.php]: A new major version (3.0) must be released with an UPGRADE.md document which contains the changes :-)

**Comment by amouhzi** [comment]
Thank you
